#!/bin/bash
# Export Wispr Flow's dictionary into ~/.hammerspoon/dictate_dictionary.lua.
# Safe to re-run; it overwrites the output file. Prints counts only.
set -euo pipefail
SRC="$HOME/Library/Application Support/Wispr Flow/flow.sqlite"
OUT="${1:-$HOME/.hammerspoon/dictate_dictionary.lua}"
if [ ! -f "$SRC" ]; then echo "Wispr Flow database not found at: $SRC" >&2; exit 1; fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cp "$SRC" "$TMP/flow.sqlite"
[ -f "$SRC-wal" ] && cp "$SRC-wal" "$TMP/flow.sqlite-wal"
[ -f "$SRC-shm" ] && cp "$SRC-shm" "$TMP/flow.sqlite-shm"

python3 - "$TMP/flow.sqlite" "$OUT" <<'EOF'
import sqlite3, sys
db, out_path = sys.argv[1], sys.argv[2]
con = sqlite3.connect(db)
rows = con.execute(
    "SELECT phrase, replacement, isSnippet FROM Dictionary WHERE isDeleted=0 ORDER BY lower(phrase)"
).fetchall()

def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

terms, repl, snippets = [], [], 0
for phrase, replacement, is_snippet in rows:
    phrase = (phrase or "").strip()
    if not phrase:
        continue
    if is_snippet:
        snippets += 1
        continue
    r = (replacement or "").strip()
    if r and r != phrase:
        repl.append((phrase.lower(), r))
    else:
        terms.append(phrase)

lines = [
    "-- Generated by scripts/import-wispr-dictionary.sh from Wispr Flow's Dictionary table.",
    "-- Re-run that script to refresh. Hand edits are fine; the script overwrites this file.",
    "return {",
    "  -- Names and vocabulary. Sent to Whisper as a spelling hint and to Claude as a vocabulary list.",
    "  terms = {",
]
lines += [f"    {q(t)}," for t in terms]
lines += ["  },", "  -- Spoken phrase -> written form. Applied case-insensitively after cleanup.", "  replacements = {"]
lines += [f"    [{q(p)}] = {q(r)}," for p, r in repl]
lines += ["  },", "}", ""]
with open(out_path, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {out_path}: {len(terms)} terms, {len(repl)} replacements, {snippets} snippets skipped")
EOF
